### ISSUE TITLE
Tests are completely broken

### ISSUE THREAD

**Issue by nickstenning** [openspending/os-upload#6]
The test don't pass. This makes it difficult to tell if my changes have broken anything.

```
> os-upload@0.1.0 test /Users/borior/code/os-upload
> ./node_modules/mocha/bin/mocha test/*.js

connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0

  Listening on 5000
․․․․․

  2 passing (3s)
  3 failing

  1) API Upload:
     Uncaught AssertionError: 401 == 200
      at /Users/borior/code/os-upload/test/test.js:21:16
      at Test.assert (/Users/borior/code/os-upload/node_modules/supertest/lib/test.js:194:3)
      at /Users/borior/code/os-upload/node_modules/supertest/lib/test.js:120:10
      at Test.Request.callback (/Users/borior/code/os-upload/node_modules/supertest/node_modules/superagent/lib/node/index.js:628:30)
      at Test.<anonymous> (/Users/borior/code/os-upload/node_modules/supertest/node_modules/superagent/lib/node/index.js:131:10)
      at Test.EventEmitter.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (/Users/borior/code/os-upload/node_modules/supertest/node_modules/superagent/lib/node/index.js:773:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)

  2) API authorizedToUpload:
     Uncaught AssertionError: false == true
      at /Users/borior/code/os-upload/test/test.js:30:7
      at Request._callback (/Users/borior/code/os-upload/lib/datastore.js:30:7)
      at Request.self.callback (/Users/borior/code/os-upload/node_modules/request/request.js:123:22)
      at Request.EventEmitter.emit (events.js:98:17)
      at Request.<anonymous> (/Users/borior/code/os-upload/node_modules/request/request.js:877:14)
      at Request.EventEmitter.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/Users/borior/code/os-upload/node_modules/request/request.js:828:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)

  3) API checks:

      + expected - actual

       {
         "fields": [
           {
      +      "name": "h1",
      -      "id": "h1",
             "description": "",
             "type": "string"
           },
           {
      +      "name": "h2",
      -      "id": "h2",
             "description": "",
             "type": "string"
           },
           {
      +      "name": "h3",
      -      "id": "h3",
             "description": "",
             "type": "string"
           }
         ]

      at error (/Users/borior/code/os-upload/node_modules/supertest/lib/test.js:208:13)
      at Test.assert (/Users/borior/code/os-upload/node_modules/supertest/lib/test.js:159:19)
      at /Users/borior/code/os-upload/node_modules/supertest/lib/test.js:120:10
      at Test.Request.callback (/Users/borior/code/os-upload/node_modules/supertest/node_modules/superagent/lib/node/index.js:628:30)
      at Test.<anonymous> (/Users/borior/code/os-upload/node_modules/supertest/node_modules/superagent/lib/node/index.js:131:10)
      at Test.EventEmitter.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (/Users/borior/code/os-upload/node_modules/supertest/node_modules/superagent/lib/node/index.js:773:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by pwalsh** [comment]
I'm closing old issues.
